export const START_LOADER = 'START_LOARDER';
export const LOGIN_USER_TYPE = 'LOGIN_USER_TYPE';
export const OPEN_MENU = 'OPEN_MENU';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_INTERNET_STATE = 'SET_INTERNET_STATE';
export const SET_SAFE_AREA = 'SET_SAFE_AREA';
export const SET_TAB = 'SET_TAB';
export const SET_BOTTOM_BAR_HEIGHT = "SET_BOTTOM_BAR_HEIGHT"
export const SET_CURRENT_LANG = "SET_CURRENT_LANG"
export const SET_LANG_STATE = "SET_LANG_STATE"

